all:
	g++  t1rm.cpp -o t1rm
	g++  t2rm.cpp -o t2rm
	g++  t3rm.cpp -o t3rm
	g++  t1rmi.cpp -o t1rmi
	g++  t2rmi.cpp -o t2rmi
	g++  t3rmi.cpp -o t3rmi
	g++  plott1rm.cpp -o response
clean:
	rm t1rm
	rm t2rm
	rm t3rm
	rm t1rmi
	rm t2rmi
	rm t3rmi
	rm response
